services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bank_account_oop_php-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: bank_account_oop_php-nginx
    restart: always
    ports:
      - 8001:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d